version: '3.9'

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      CONFIG_PORT: ${CONFIG_PORT}
      EMAIL: ${EMAIL}
    ports:
      - "${CONFIG_PORT}:2053"
      - "2096:2096"
      - "443:443"
    tty: true
    restart: unless-stopped

  backend:
    image: torikki/team_418:latest
    environment:
      XUI_LOGIN: ${XUI_LOGIN}
      XUI_PASS: ${XUI_PASS}
      ADMIN_TELEGRAM_ID: ${ADMIN_IDS}
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}