version: "3.9"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_USERNAME: ${XUI_USERNAME}
      XUI_PASSWORD: ${XUI_PASSWORD}
      XUI_PANEL_PORT: ${XUI_PANEL_PORT}
      XUI_HOSTNAME: ${XUI_HOSTNAME}
      XUI_EMAIL: ${XUI_EMAIL}
      XUI_BASE_PATH: ""
      TGTOKEN: ${TGTOKEN}
      ADMINID: ${ADMINID}
    volumes:
      - "$PWD/cert/:/root/cert/"
      - "$PWD/db/:/etc/x-ui/"
    ports:
      - "2096:2096"
      - "443:443"
      - "${XUI_PANEL_PORT}:2053"
    tty: true
    restart: unless-stopped
