version: "3.9"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_USERNAME: ${XUI_USERNAME}
      XUI_PASSWORD: ${XUI_PASSWORD}
      XUI_PANEL_PORT: ${XUI_PANEL_PORT}
      XUI_HOSTNAME: ${XUI_HOSTNAME}
      XUI_EMAIL: ${XUI_EMAIL}
      XUI_BASE_PATH: ""
      TGTOKEN: ${TGTOKEN}
      ADMINID: ${ADMINID}
    volumes:
      - "$PWD/cert/:/root/cert/"
      - "$PWD/db/:/etc/x-ui/"
    ports:
      - "${XUI_PANEL_PORT}:2053"
      - "2096:2096"
      - "443:443"
    tty: true
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XUI_LOGIN: ${XUI_USERNAME}
      XUI_PASS: ${XUI_PASSWORD}
      ADMIN_TELEGRAM_ID: ${ADMINID}
      TELEGRAM_API_TOKEN: ${TGTOKEN}
      XUI_HOSTNAME: ${XUI_HOSTNAME}
      XUI_URL: "http://3x-ui:2053"
    volumes:
      - "$PWD/db/:/db/"
